from .models import User

def add_data():
    # -- admins --
    User.objects.create_superuser(
        username="admin123",
        password="haslo123",
        name="admin_name",
        surname="admin_surname"
    )
    # -- teachers --
    User.objects.create_teacher(
        username="teacher1",
        password="teacher_user",
        name="Jan",
        surname="Kowalski"
    )
    User.objects.create_teacher(
        username="teacher2",
        password="teacher_user",
        name="Anna",
        surname="Kowalska"
    )
    User.objects.create_teacher(
        username="teacher2",
        password="teacher_user",
        name="Andrzej",
        surname="Nowak"
    )
    User.objects.create_teacher(
        username="teacher3",
        password="teacher_user",
        name="Arleta",
        surname="Gałga"
    )
    User.objects.create_teacher(
        username="teacher4",
        password="teacher_user",
        name="Marzena",
        surname="Domańska"
    )
    User.objects.create_teacher(
        username="teacher5",
        password="teacher_user",
        name="Maria",
        surname="Szczerska"
    )
    # -- students --
    User.objects.create_student(
        username="student1",
        password="student_user",
        name="Adam",
        surname="Stańczyk"
    )
    User.objects.create_student(
        username="student2",
        password="student_user",
        name="Michał",
        surname="Wielosiński"
    )
    User.objects.create_student(
        username="student3",
        password="student_user",
        name="Jaroslaw",
        surname="Tusk"
    )
    User.objects.create_student(
        username="student4",
        password="student_user",
        name="Donald",
        surname="Kaczyński"
    )
    User.objects.create_student(
        username="student5",
        password="student_user",
        name="Beata",
        surname="Kopacz",
    )
    User.objects.create_student(
        username="student6",
        password="student_user",
        name="Ewa",
        surname="Szydlo",
    )
    User.objects.create_student(
        username="student7",
        password="student_user",
        name="Beata",
        surname="Kopacz"
    )
    User.objects.create_student(
        username="student8",
        password="student_user",
        name="Piotr",
        surname="Stolarski",
    )
    User.objects.create_student(
        username="student9",
        password="student_user",
        name="Maciej",
        sname="Andrzej",
        surname="Rudnik"
    )
    User.objects.create_student(
        username="student10",
        password="student_user",
        name="Mariusz",
        sname="Józef",
        surname="Poniatowski"
    )
    User.objects.create_student(
        username="student11",
        password="student_user",
        name="Anna",
        sname="Maria",
        surname="Górniak"
    )
    User.objects.create_student(
        username="student12",
        password="student_user",
        name="Edyta",
        surname="Jopek"
    )
    User.objects.create_student(
        username="student13",
        password="student_user",
        name="Arkadiusz",
        surname="Musiał"
    )
    User.objects.create_student(
        username="student14",
        password="student_user",
        name="Tomasz",
        surname="Malarz"
    )
    User.objects.create_student(
        username="student15",
        password="student_user",
        name="Katarzyna",
        surname="Popowska"
    )